name = "part1"
description = "Advent of Code Day 5 Part 1"
version = "0.1.0-dev"

authors = ["Danny Wilkins"]
maintainers = ["Danny Wilkins <example@example.com>"]
licenses = "MIT"
website = ""
tags = []

executables = ["part1"]
